// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gckytkfspzrcqoewpyox.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdja3l0a2ZzcHpyY3FvZXdweW94Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNzAwNTEsImV4cCI6MjA2Njk0NjA1MX0.ogZ6yEMSaEH1WR6V3GfAu7nFvjuPkGnOBFgrXXuRGYs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});